name: Refresh data

on:
  workflow_dispatch: {}
  schedule:
    # Every 30 minutes as a baseline (UTC)
    - cron: "*/30 * * * *"
    # Extra frequent on Saturdays (UTC ~ gameday), every 10 minutes 12:00–23:59 UTC
    - cron: "*/10 12-23 * * 6"

permissions:
  contents: write

concurrency:
  group: data-refresh
  cancel-in-progress: false

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps for scripts
        run: npm i --no-save ajv@8 ajv-formats@2

      - name: Fetch & build data JSON
        env:
          CFBD_API_KEY: ${{ secrets.CFBD_API_KEY }}
          FSQ_API_KEY:  ${{ secrets.FSQ_API_KEY }}
        run: node scripts/fetch-data.js

      - name: Validate JSON
        run: node scripts/validate-data.js

      - name: Commit updated JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.json || true
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore(data): refresh"
            git push
          fi
